
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[371] =
    {   0,
        0,    0,   61,   60,   48,   48,   59,   54,   44,   60,
       51,   49,   50,   53,   45,   46,   47,   60,   60,   42,
       43,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   58,
        0,   53,    0,    0,    0,   56,   55,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,   57,   53,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   17,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   58,   58,    0,   52,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,   15,    0,    0,    0,    0,    0,    0,
       34,   33,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    0,   16,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   31,   22,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2,   11,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    5,    0,    4,    0,    0,    0,
        0,    0,   35,    0,    0,    0,    0,    7,    0,    0,
        0,    0,   27,    0,    0,    0,    0,   26,    3,    0,
        0,    0,    0,    0,    0,    0,    0,   21,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   19,    0,
        0,    0,    0,    0,    0,   18,    0,    6,   24,    0,
        0,    0,    0,    0,    0,   37,    0,    0,    0,    0,

        0,   41,    0,    0,   36,    0,    8,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   40,
        0,   38,    0,    0,    0,    0,    0,    0,   29,    9,
        0,    0,    0,   20,    0,    0,    0,   10,    0,    0,
        0,    0,   23,    0,   39,    0,    0,    0,    0,    0,
        0,    0,    0,   30,    0,    0,    0,    0,    0,    0,
       12,    0,    0,   13,   14,    0,   32,    0,   25,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        3,    5,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,   10,    1,   11,   12,   13,
       13,   13,   13,   13,   13,   13,   14,   15,    1,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   16,
       16,   21,   22,   16,   16,   16,   16,   23,   24,   25,
       16,   16,   26,   27,   16,   16,   16,   16,   16,   16,
       28,    1,   29,    1,    1,    1,   30,   31,   32,   33,

       34,   35,   36,   16,   37,   38,   39,   40,   41,   42,
       43,   44,   16,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,    1,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    1,    2,    1,    3,    3,    1,    1,    3,
        3,    3,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1
    } ;

static const flex_int16_t yy_base[376] =
    {   0,
        0,   54,   81, 1639, 1639, 1639, 1639,  104, 1639,    5,
        9,   13,   19,   25, 1639, 1639, 1639,   49,   32, 1639,
     1639,   69,   34,   39,   68,   89,  152,   80,  154,  159,
      161,  166,   96,  168,  173,  192,  194,  175,  201,   39,
       80,  208,   33,   22,   57, 1639, 1639,  106,  199,  207,
      217,  226,  235,  237,  243,  245,  255,  257,  262,  264,
      269,  282,  287,  289,  296,  302,  308,  310,  315,  320,
      322,  327,  333,  344,  349,  349,  358,  364,  370,    2,
        9,  379,  386,  388,  393,  395,  401,  407,  412,  414,
      419,  424,  431,  438,  444,  450,  455, 1639,  457,  463,

      468,  470,  475,  485,  487,  497,  499,  504,  513,  520,
      525,  527,  534,  539,  540,  545,    8, 1639,  555,  563,
      570,  572,  577,  579,  584,  586,  592,  600,  611,  621,
      623,  628,  636,  641,  651,  660,  666,  671,  673,  678,
      683,  685,  691,  696,  701,  703,  714,  716,  721,  726,
      731,  733,  738,  740,  747,  753,  763,  768,  775,  782,
      784,  789,  791,  797,  802,  808,  813,  822,  827,  833,
      840,  845, 1639, 1639,  847,  852,  857,  859,  865,  870,
     1639, 1639,  880,  886,  891,  893,  898,  903,  910, 1639,
      915,  917, 1639,  922,  927,  934,  941,  943,  951,  949,

      956,  958,  965, 1639, 1639,  977,  979,  986,  988,  993,
      995, 1001, 1003, 1008, 1010, 1020, 1022, 1033, 1035, 1041,
     1043, 1049, 1054, 1639, 1639, 1059, 1061, 1066, 1068, 1073,
     1075, 1086, 1092, 1097, 1639, 1099, 1639, 1109, 1114, 1116,
     1122, 1130, 1639, 1139, 1141, 1146, 1148, 1639, 1154, 1159,
     1161, 1166, 1639, 1173, 1175, 1180, 1195, 1639, 1639, 1197,
     1202, 1204, 1211, 1213, 1218, 1220, 1225, 1639, 1227, 1235,
     1240, 1247, 1249, 1255, 1260, 1262, 1267, 1272, 1639, 1274,
     1280, 1285, 1292, 1297, 1299, 1639, 1304, 1639, 1639, 1306,
     1311, 1317, 1319, 1324, 1329, 1639, 1335, 1337, 1342, 1354,

     1356, 1639, 1366, 1368, 1639, 1374, 1639, 1379, 1388, 1394,
     1396, 1402, 1407, 1409, 1414, 1416, 1421, 1427, 1432, 1639,
     1434, 1639, 1439, 1446, 1453, 1455, 1462, 1464, 1639, 1639,
     1469, 1471, 1479, 1639, 1481, 1486, 1491, 1639, 1493, 1502,
     1507, 1513, 1639, 1521, 1639, 1526, 1528, 1533, 1535, 1540,
     1547, 1549, 1554, 1639, 1559, 1564, 1566, 1571, 1573, 1578,
     1639, 1584, 1591, 1639, 1639, 1596, 1639, 1601, 1639, 1639,
     1629, 1632,   31,    7, 1635
    } ;

static const flex_int16_t yy_def[376] =
    {   0,
      371,  371,  370,  370,  370,  370,  370,  370,  370,  370,
      372,  372,  372,  372,  370,  370,  370,  370,  370,  370,
      370,  373,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  375,
      370,  372,  370,  370,  373,  370,  370,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  370,  375,  370,  372,  370,
      370,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  370,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  370,  375,  370,  370,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  370,  370,  374,  374,  374,  374,  374,  374,
      370,  370,  374,  374,  374,  374,  374,  374,  374,  370,
      374,  374,  370,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  370,  370,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  370,  370,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  370,  374,  370,  374,  374,  374,
      374,  374,  370,  374,  374,  374,  374,  370,  374,  374,
      374,  374,  370,  374,  374,  374,  374,  370,  370,  374,
      374,  374,  374,  374,  374,  374,  374,  370,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  370,  374,
      374,  374,  374,  374,  374,  370,  374,  370,  370,  374,
      374,  374,  374,  374,  374,  370,  374,  374,  374,  374,

      374,  370,  374,  374,  370,  374,  370,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  370,
      374,  370,  374,  374,  374,  374,  374,  374,  370,  370,
      374,  374,  374,  370,  374,  374,  374,  370,  374,  374,
      374,  374,  370,  374,  370,  374,  374,  374,  374,  374,
      374,  374,  374,  370,  374,  374,  374,  374,  374,  374,
      370,  374,  374,  370,  370,  374,  370,  374,  370,    0,
      370,  370,  370,  370,  370
    } ;

static const flex_int16_t yy_nxt[1695] =
    {   0,
      370,    5,    6,    6,    7,    6,    8,    9,   10,   48,
       11,   12,   13,   14,   15,   40,   40,   40,   40,   42,
       42,   42,   42,   42,   42,   42,   42,   16,   17,   42,
       42,   42,   42,   45,   18,   42,   42,   42,   42,   45,
       47,  118,  118,   45,   45,   47,   19,  117,   45,   77,
       77,   77,   77,   20,   21,    5,    6,    6,    7,    6,
        8,    9,   10,   46,   11,   12,   13,   14,   15,   81,
       49,   50,   80,   45,   47,   46,   44,   45,   43,   51,
      370,   16,   17,  370,   52,   45,   47,  370,   18,   45,
       78,   78,   78,   78,   45,   47,  370,  370,   45,  370,

       19,   45,   47,  370,  370,   45,  370,   20,   21,   22,
       53,   45,   47,   22,  370,   45,   59,  370,   54,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   55,   66,   24,   25,   26,   27,   23,   28,   29,
       30,   31,   23,   32,   33,   34,   23,   35,   23,   36,
       37,   23,   38,   39,   23,   23,   23,   45,   47,   45,
       47,   45,  370,   45,   45,   47,   45,   47,   45,  370,
       45,   45,   47,   45,   47,   45,  370,   45,   45,   47,
       45,   47,   45,   60,   45,   56,  370,  370,   57,  370,
       63,   61,  370,  370,   62,   64,   58,   45,   47,   45,

       47,   45,   65,   45,   45,   47,   45,   47,   45,  370,
       45,   73,   45,   47,  370,   67,   45,   68,   79,   79,
       79,   79,   45,   47,  370,  370,   45,  370,   69,  370,
       74,   45,   47,  370,   70,   45,   72,   75,   71,   83,
       45,   47,   45,   47,   45,   82,   45,  370,   45,   47,
       45,   47,   45,  370,   45,  370,  370,   85,  370,   84,
       45,   47,   45,   47,   45,  370,   45,   45,   47,   45,
       47,   45,  370,   45,   45,   98,   86,  370,   45,  370,
      370,  370,   88,   87,   89,  370,   94,   45,   47,  370,
       90,   45,   45,   47,   45,   47,   45,  370,   45,   91,

       92,   45,   47,   93,   97,   45,   95,   45,   47,  370,
      370,   45,   96,   45,   47,   45,   47,   45,  100,   45,
       45,   47,  370,   99,   45,   45,   47,   45,   47,   45,
      370,   45,   45,   47,  101,  370,   45,  370,   45,   47,
      370,  102,   45,  103,  370,  370,  106,  104,  105,   45,
       47,  110,  107,   45,   45,   47,  370,  370,   45,  115,
      115,  115,  115,  370,  109,  370,  370,  108,  116,  116,
      116,  116,  370,  111,   78,   78,   78,   78,  112,  113,
       79,   79,   79,   79,   45,   47,  370,  370,   45,  370,
      114,   45,   47,   45,   47,   45,  370,   45,   45,   47,

       45,   47,   45,  370,   45,  370,   45,   47,  370,  120,
       45,  370,   45,   47,  370,  119,   45,   45,   47,   45,
       47,   45,  370,   45,   45,   47,  122,  370,   45,   45,
       47,  370,  370,   45,  124,  121,   45,   47,  370,  370,
       45,  370,  123,   45,   47,  127,  370,   45,  370,   45,
       47,  370,  128,   45,  125,   45,   47,  370,  126,   45,
       45,   47,   45,   47,   45,  370,   45,  130,   45,   47,
      129,  370,   45,   45,   47,   45,   47,   45,  370,   45,
       45,   47,  370,  133,   45,  370,  370,  131,  134,  132,
       45,   47,   45,   47,   45,  370,   45,  370,  370,  135,

      370,  136,   45,   47,   45,   47,   45,  370,   45,   45,
       47,  139,  370,   45,  137,  370,  138,  141,   45,   47,
      370,  370,   45,  370,  140,   45,   47,  370,  142,   45,
       45,   47,   45,   47,   45,  370,   45,  145,  370,   45,
       47,  370,  144,   45,   45,   47,  370,  370,   45,  143,
      115,  115,  115,  115,  148,  116,  116,  116,  116,  146,
       45,   47,  370,  370,   45,  370,  147,  150,   45,   47,
      370,  370,   45,  370,  149,   45,   47,   45,   47,   45,
      151,   45,   45,   47,   45,   47,   45,  370,   45,   45,
       47,   45,   47,   45,  370,   45,  370,   45,   47,  370,

      370,   45,  370,  152,  153,   45,   47,  370,  370,   45,
      370,  154,  370,  155,  157,  370,   45,   47,  370,  159,
       45,  370,  156,  370,  158,  160,   45,   47,   45,   47,
       45,  161,   45,   45,   47,  370,  370,   45,  370,  164,
      370,   45,   47,  370,  165,   45,   45,   47,  370,  166,
       45,  370,  370,  163,  370,  162,   45,   47,  370,  370,
       45,  370,  169,  370,  370,   45,   47,  170,  168,   45,
      370,   45,  173,  370,  167,   45,   45,  174,   45,   47,
       45,  370,   45,   45,   47,  370,  370,   45,   45,   47,
       45,   47,   45,  370,   45,  171,   45,   47,  176,  370,

       45,   45,   47,  172,  370,   45,   45,  181,   45,  182,
       45,  370,   45,  175,  370,  370,  177,  370,  178,   45,
       47,   45,   47,   45,  179,   45,   45,   47,  370,  180,
       45,   45,   47,  370,  370,   45,   45,   47,   45,   47,
       45,  370,   45,   45,  190,   45,   47,   45,  370,   45,
      185,  370,   45,   47,  370,  184,   45,  370,   45,  193,
      370,  183,   45,  370,  187,  370,  189,  188,   45,   47,
      186,  370,   45,   45,   47,  370,  370,   45,  370,  192,
       45,   47,  370,  370,   45,  370,  191,   45,   47,   45,
       47,   45,  370,   45,   45,   47,   45,   47,   45,  370,

       45,  370,   45,   47,  370,  194,   45,   45,   47,  195,
      370,   45,  370,   45,   47,  370,  196,   45,   45,  204,
      370,  370,   45,  197,  200,  199,  370,   45,  205,  370,
      198,   45,   45,   47,  202,  370,   45,  370,   45,   47,
      370,  201,   45,  370,  203,   45,   47,  370,  370,   45,
       45,   47,   45,   47,   45,  370,   45,   45,   47,  206,
      370,   45,   45,   47,   45,   47,   45,  370,   45,  370,
       45,   47,  370,  208,   45,   45,   47,  370,  370,   45,
      370,  211,  214,  213,  207,   45,   47,  209,  370,   45,
      370,   45,   47,  370,  210,   45,   45,   47,   45,   47,

       45,  212,   45,   45,   47,  217,  370,   45,   45,   47,
      218,  370,   45,  370,  215,   45,  224,  370,  220,   45,
       45,  225,   45,   47,   45,  216,   45,   45,   47,  370,
      219,   45,   45,   47,  370,  370,   45,  370,  221,   45,
       47,  370,  222,   45,  223,  370,   45,   47,   45,   47,
       45,  370,   45,  226,   45,   47,   45,   47,   45,  370,
       45,   45,   47,   45,  235,   45,  227,   45,  370,  370,
       45,   47,  228,  230,   45,  370,  370,  370,  370,  231,
      229,  232,   45,  237,   45,   47,   45,  370,   45,  234,
      233,   45,   47,   45,   47,   45,  370,   45,   45,   47,

       45,   47,   45,  239,   45,  236,   45,  243,   45,   47,
       45,  370,   45,   45,   47,   45,   47,   45,  370,   45,
      370,  370,  238,  370,  244,   45,  248,   45,   47,   45,
      370,   45,  370,  241,  240,  370,  242,  246,   45,   47,
       45,   47,   45,  370,   45,  245,   45,   47,   45,  253,
       45,  370,   45,  251,   45,   47,  247,  370,   45,   45,
       47,  249,  250,   45,   45,   47,   45,   47,   45,  370,
       45,   45,  258,   45,  259,   45,  370,   45,   45,   47,
       45,   47,   45,  370,   45,  370,  370,  252,  370,  255,
      370,   45,   47,  370,  254,   45,  370,   45,   47,  370,

      256,   45,   45,   47,   45,   47,   45,  370,   45,  260,
      370,  370,  257,  370,   45,   47,  370,  261,   45,   45,
       47,   45,  268,   45,  370,   45,  264,   45,   47,  370,
      370,   45,  265,  262,  370,   45,   47,  370,  263,   45,
      269,  370,  266,  267,   45,   47,   45,   47,   45,  370,
       45,   45,   47,   45,   47,   45,  370,   45,  370,   45,
       47,  370,  270,   45,   45,   47,   45,   47,   45,  370,
       45,   45,   47,  271,  370,   45,  370,  272,   45,  279,
       45,   47,   45,  370,   45,   45,   47,  275,  370,   45,
      370,  370,  273,  370,  276,  278,  370,  280,  370,  274,

       45,   47,   45,   47,   45,  277,   45,   45,   47,   45,
       47,   45,  370,   45,  370,  281,   45,  286,   45,   47,
       45,  282,   45,   45,  288,   45,  289,   45,  370,   45,
       45,   47,   45,   47,   45,  370,   45,  370,  283,  370,
       45,   47,  370,  284,   45,   45,   47,  370,  370,   45,
      285,  287,   45,   47,   45,   47,   45,  370,   45,  293,
       45,  296,  370,  291,   45,   45,   47,   45,   47,   45,
      290,   45,   45,   47,  292,  370,   45,   45,   47,   45,
       47,   45,  295,   45,  370,   45,  302,  370,  294,   45,
       45,   47,  370,  370,   45,  298,  299,   45,   47,  370,

      297,   45,   45,  305,   45,   47,   45,  370,   45,   45,
      307,   45,   47,   45,  370,   45,   45,   47,  300,  370,
       45,  301,   45,   47,   45,   47,   45,  304,   45,   45,
       47,  370,  306,   45,   45,   47,  303,  370,   45,  308,
       45,   47,   45,   47,   45,  370,   45,   45,   47,  370,
      370,   45,  370,  310,  370,  370,  309,  370,  311,   45,
       47,   45,   47,   45,  313,   45,  370,  370,  314,  370,
      312,   45,   47,   45,  320,   45,  370,   45,  370,   45,
       47,  370,  315,   45,   45,  322,  370,  370,   45,  370,
      317,  316,  370,   45,   47,  370,  318,   45,  370,   45,

       47,   45,   47,   45,  370,   45,  321,   45,   47,  319,
      370,   45,   45,   47,   45,   47,   45,  370,   45,   45,
      329,   45,  330,   45,  370,   45,   45,   47,  370,  325,
       45,  370,   45,   47,  323,  324,   45,   45,   47,   45,
      334,   45,  370,   45,   45,   47,  370,  326,   45,  327,
      328,   45,   47,  370,  370,   45,  370,  332,   45,   47,
       45,  338,   45,  370,   45,  333,  331,   45,   47,   45,
       47,   45,  370,   45,   45,   47,   45,   47,   45,  370,
       45,  336,  370,  335,   45,  343,   45,   47,   45,  370,
       45,   45,  345,  337,  370,   45,   45,   47,   45,   47,

       45,  370,   45,  370,  342,  370,  339,   45,   47,  370,
      340,   45,   45,   47,  370,  341,   45,  344,   45,   47,
      370,  370,   45,  370,  346,  370,   45,   47,  370,  347,
       45,   45,   47,   45,   47,   45,  370,   45,   45,  354,
       45,   47,   45,  349,   45,   45,   47,  348,  370,   45,
      370,  351,   45,   47,   45,   47,   45,  350,   45,   45,
       47,  353,  370,   45,   45,   47,  355,  352,   45,   45,
      361,   45,   47,   45,  370,   45,   45,   47,   45,  364,
       45,  370,   45,   45,  365,  356,  370,   45,  370,   45,
       47,  370,  370,   45,  357,  358,   45,  367,  370,  359,

       45,   45,   47,  370,  360,   45,   45,  369,  370,  370,
       45,  370,  362,  370,  370,  370,  363,  366,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  368,    4,
        4,    4,   41,  370,   41,   76,  370,   76,    3,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370

    } ;

static const flex_int16_t yy_chk[1695] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    1,    1,  374,
        1,    1,    1,    1,    1,   10,   10,   10,   10,   11,
       11,   11,   11,   12,   12,   12,   12,    1,    1,   13,
       13,   13,   13,  373,    1,   14,   14,   14,   14,   23,
       23,  117,   81,   23,   24,   24,    1,   80,   24,   40,
       40,   40,   40,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,   45,    2,    2,    2,    2,    2,   44,
       24,   24,   43,   25,   25,   22,   19,   25,   18,   24,
        3,    2,    2,    0,   24,   28,   28,    0,    2,   28,
       41,   41,   41,   41,   26,   26,    0,    0,   26,    0,

        2,   33,   33,    0,    0,   33,    0,    2,    2,    8,
       25,   48,   48,    8,    0,   48,   28,    0,   26,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   26,   33,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,   27,   27,   29,
       29,   27,    0,   29,   30,   30,   31,   31,   30,    0,
       31,   32,   32,   34,   34,   32,    0,   34,   35,   35,
       38,   38,   35,   29,   38,   27,    0,    0,   27,    0,
       31,   30,    0,    0,   30,   32,   27,   36,   36,   37,

       37,   36,   32,   37,   49,   49,   39,   39,   49,    0,
       39,   38,   50,   50,    0,   34,   50,   35,   42,   42,
       42,   42,   51,   51,    0,    0,   51,    0,   36,    0,
       39,   52,   52,    0,   36,   52,   37,   39,   36,   50,
       53,   53,   54,   54,   53,   49,   54,    0,   55,   55,
       56,   56,   55,    0,   56,    0,    0,   52,    0,   51,
       57,   57,   58,   58,   57,    0,   58,   59,   59,   60,
       60,   59,    0,   60,   61,   61,   53,    0,   61,    0,
        0,    0,   55,   54,   55,    0,   58,   62,   62,    0,
       56,   62,   63,   63,   64,   64,   63,    0,   64,   57,

       57,   65,   65,   57,   60,   65,   59,   66,   66,    0,
        0,   66,   59,   67,   67,   68,   68,   67,   63,   68,
       69,   69,    0,   62,   69,   70,   70,   71,   71,   70,
        0,   71,   72,   72,   64,    0,   72,    0,   73,   73,
        0,   65,   73,   66,    0,    0,   68,   67,   67,   74,
       74,   71,   68,   74,   75,   75,    0,    0,   75,   76,
       76,   76,   76,    0,   70,    0,    0,   69,   77,   77,
       77,   77,    0,   72,   78,   78,   78,   78,   73,   74,
       79,   79,   79,   79,   82,   82,    0,    0,   82,    0,
       75,   83,   83,   84,   84,   83,    0,   84,   85,   85,

       86,   86,   85,    0,   86,    0,   87,   87,    0,   83,
       87,    0,   88,   88,    0,   82,   88,   89,   89,   90,
       90,   89,    0,   90,   91,   91,   85,    0,   91,   92,
       92,    0,    0,   92,   87,   84,   93,   93,    0,    0,
       93,    0,   86,   94,   94,   90,    0,   94,    0,   95,
       95,    0,   91,   95,   88,   96,   96,    0,   89,   96,
       97,   97,   99,   99,   97,    0,   99,   93,  100,  100,
       92,    0,  100,  101,  101,  102,  102,  101,    0,  102,
      103,  103,    0,   96,  103,    0,    0,   94,   97,   95,
      104,  104,  105,  105,  104,    0,  105,    0,    0,   99,

        0,  100,  106,  106,  107,  107,  106,    0,  107,  108,
      108,  103,    0,  108,  101,    0,  102,  105,  109,  109,
        0,    0,  109,    0,  104,  110,  110,    0,  106,  110,
      111,  111,  112,  112,  111,    0,  112,  108,    0,  113,
      113,    0,  107,  113,  114,  114,    0,    0,  114,  106,
      115,  115,  115,  115,  111,  116,  116,  116,  116,  109,
      119,  119,    0,    0,  119,    0,  110,  113,  120,  120,
        0,    0,  120,    0,  112,  121,  121,  122,  122,  121,
      114,  122,  123,  123,  124,  124,  123,    0,  124,  125,
      125,  126,  126,  125,    0,  126,    0,  127,  127,    0,

        0,  127,    0,  119,  120,  128,  128,    0,    0,  128,
        0,  121,    0,  122,  124,    0,  129,  129,    0,  126,
      129,    0,  123,    0,  125,  127,  130,  130,  131,  131,
      130,  128,  131,  132,  132,    0,    0,  132,    0,  131,
        0,  133,  133,    0,  131,  133,  134,  134,    0,  131,
      134,    0,    0,  130,    0,  129,  135,  135,    0,    0,
      135,    0,  134,    0,    0,  136,  136,  134,  133,  136,
        0,  137,  137,    0,  132,  137,  138,  138,  139,  139,
      138,    0,  139,  140,  140,    0,    0,  140,  141,  141,
      142,  142,  141,    0,  142,  135,  143,  143,  140,    0,

      143,  144,  144,  136,    0,  144,  145,  145,  146,  146,
      145,    0,  146,  139,    0,    0,  141,    0,  142,  147,
      147,  148,  148,  147,  143,  148,  149,  149,    0,  144,
      149,  150,  150,    0,    0,  150,  151,  151,  152,  152,
      151,    0,  152,  153,  153,  154,  154,  153,    0,  154,
      149,    0,  155,  155,    0,  148,  155,    0,  156,  156,
        0,  147,  156,    0,  151,    0,  152,  151,  157,  157,
      150,    0,  157,  158,  158,    0,    0,  158,    0,  155,
      159,  159,    0,    0,  159,    0,  154,  160,  160,  161,
      161,  160,    0,  161,  162,  162,  163,  163,  162,    0,

      163,    0,  164,  164,    0,  157,  164,  165,  165,  158,
        0,  165,    0,  166,  166,    0,  159,  166,  167,  167,
        0,    0,  167,  160,  163,  162,    0,  168,  168,    0,
      161,  168,  169,  169,  165,    0,  169,    0,  170,  170,
        0,  164,  170,    0,  166,  171,  171,    0,    0,  171,
      172,  172,  175,  175,  172,    0,  175,  176,  176,  169,
        0,  176,  177,  177,  178,  178,  177,    0,  178,    0,
      179,  179,    0,  171,  179,  180,  180,    0,    0,  180,
        0,  176,  179,  178,  170,  183,  183,  172,    0,  183,
        0,  184,  184,    0,  175,  184,  185,  185,  186,  186,

      185,  177,  186,  187,  187,  184,    0,  187,  188,  188,
      184,    0,  188,    0,  180,  189,  189,    0,  186,  189,
      191,  191,  192,  192,  191,  183,  192,  194,  194,    0,
      185,  194,  195,  195,    0,    0,  195,    0,  186,  196,
      196,    0,  187,  196,  188,    0,  197,  197,  198,  198,
      197,    0,  198,  192,  200,  200,  199,  199,  200,    0,
      199,  201,  201,  202,  202,  201,  194,  202,    0,    0,
      203,  203,  195,  197,  203,    0,    0,    0,    0,  198,
      196,  199,  206,  206,  207,  207,  206,    0,  207,  201,
      200,  208,  208,  209,  209,  208,    0,  209,  210,  210,

      211,  211,  210,  208,  211,  203,  212,  212,  213,  213,
      212,    0,  213,  214,  214,  215,  215,  214,    0,  215,
        0,    0,  207,    0,  212,  216,  216,  217,  217,  216,
        0,  217,    0,  210,  209,    0,  211,  214,  218,  218,
      219,  219,  218,    0,  219,  213,  220,  220,  221,  221,
      220,    0,  221,  219,  222,  222,  215,    0,  222,  223,
      223,  217,  218,  223,  226,  226,  227,  227,  226,    0,
      227,  228,  228,  229,  229,  228,    0,  229,  230,  230,
      231,  231,  230,    0,  231,    0,    0,  220,    0,  223,
        0,  232,  232,    0,  222,  232,    0,  233,  233,    0,

      226,  233,  234,  234,  236,  236,  234,    0,  236,  230,
        0,    0,  227,    0,  238,  238,    0,  231,  238,  239,
      239,  240,  240,  239,    0,  240,  234,  241,  241,    0,
        0,  241,  236,  232,    0,  242,  242,    0,  233,  242,
      241,    0,  238,  239,  244,  244,  245,  245,  244,    0,
      245,  246,  246,  247,  247,  246,    0,  247,    0,  249,
      249,    0,  242,  249,  250,  250,  251,  251,  250,    0,
      251,  252,  252,  244,    0,  252,    0,  245,  254,  254,
      255,  255,  254,    0,  255,  256,  256,  249,    0,  256,
        0,    0,  246,    0,  250,  252,    0,  255,    0,  247,

      257,  257,  260,  260,  257,  251,  260,  261,  261,  262,
      262,  261,    0,  262,    0,  256,  263,  263,  264,  264,
      263,  257,  264,  265,  265,  266,  266,  265,    0,  266,
      267,  267,  269,  269,  267,    0,  269,    0,  260,    0,
      270,  270,    0,  261,  270,  271,  271,    0,    0,  271,
      262,  264,  272,  272,  273,  273,  272,    0,  273,  271,
      274,  274,    0,  269,  274,  275,  275,  276,  276,  275,
      267,  276,  277,  277,  270,    0,  277,  278,  278,  280,
      280,  278,  273,  280,    0,  281,  281,    0,  272,  281,
      282,  282,    0,    0,  282,  276,  277,  283,  283,    0,

      275,  283,  284,  284,  285,  285,  284,    0,  285,  287,
      287,  290,  290,  287,    0,  290,  291,  291,  278,    0,
      291,  280,  292,  292,  293,  293,  292,  283,  293,  294,
      294,    0,  285,  294,  295,  295,  282,    0,  295,  290,
      297,  297,  298,  298,  297,    0,  298,  299,  299,    0,
        0,  299,    0,  292,    0,    0,  291,    0,  293,  300,
      300,  301,  301,  300,  295,  301,    0,    0,  297,    0,
      294,  303,  303,  304,  304,  303,    0,  304,    0,  306,
      306,    0,  298,  306,  308,  308,    0,    0,  308,    0,
      300,  299,    0,  309,  309,    0,  301,  309,    0,  310,

      310,  311,  311,  310,    0,  311,  306,  312,  312,  303,
        0,  312,  313,  313,  314,  314,  313,    0,  314,  315,
      315,  316,  316,  315,    0,  316,  317,  317,    0,  311,
      317,    0,  318,  318,  309,  310,  318,  319,  319,  321,
      321,  319,    0,  321,  323,  323,    0,  312,  323,  313,
      314,  324,  324,    0,    0,  324,    0,  318,  325,  325,
      326,  326,  325,    0,  326,  319,  317,  327,  327,  328,
      328,  327,    0,  328,  331,  331,  332,  332,  331,    0,
      332,  324,    0,  323,  333,  333,  335,  335,  333,    0,
      335,  336,  336,  325,    0,  336,  337,  337,  339,  339,

      337,    0,  339,    0,  332,    0,  327,  340,  340,    0,
      328,  340,  341,  341,    0,  331,  341,  335,  342,  342,
        0,    0,  342,    0,  337,    0,  344,  344,    0,  339,
      344,  346,  346,  347,  347,  346,    0,  347,  348,  348,
      349,  349,  348,  341,  349,  350,  350,  340,    0,  350,
        0,  344,  351,  351,  352,  352,  351,  342,  352,  353,
      353,  347,    0,  353,  355,  355,  349,  346,  355,  356,
      356,  357,  357,  356,    0,  357,  358,  358,  359,  359,
      358,    0,  359,  360,  360,  350,    0,  360,    0,  362,
      362,    0,    0,  362,  351,  352,  363,  363,    0,  353,

      363,  366,  366,    0,  355,  366,  368,  368,    0,    0,
      368,    0,  357,    0,    0,    0,  358,  362,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  366,  371,
      371,  371,  372,    0,  372,  375,    0,  375,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[61] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "myParser.l"
#line 2 "myParser.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"
#line 971 "lex.yy.c"
/* regular expressions */
#line 973 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "myParser.l"


#line 1193 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 371 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1639 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "myParser.l"
{return T_LAST;}             
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "myParser.l"
{return T_ACTIVE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "myParser.l"
{return T_CONTENT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "myParser.l"
{return T_GAMEID;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "myParser.l"
{return T_DRAWID;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 35 "myParser.l"
{return T_DRAWTIME;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 36 "myParser.l"
{return T_STATUS;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 37 "myParser.l"
{return T_DRAWBREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 38 "myParser.l"
{return T_VISUALDRAW;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "myParser.l"
{return T_PRICEPOINTS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 40 "myParser.l"
{return T_AMOUNT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "myParser.l"
{return T_WINNINGNUMBERS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 42 "myParser.l"
{return T_PRIZECATEGORIES;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "myParser.l"
{return T_WAGERSTATISTICS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "myParser.l"
{return T_LIST;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "myParser.l"
{return T_BONUS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "myParser.l"
{return T_ID;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "myParser.l"
{return T_DIVIDENT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "myParser.l"
{return T_WINNERS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "myParser.l"
{return T_DISTRIBUTED;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "myParser.l"
{return T_JACKPOT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "myParser.l"
{return T_FIXED;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "myParser.l"
{return T_CATEGORYTYPE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "myParser.l"
{return T_GAMETYPE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "myParser.l"
{return T_MINIMUMDISTRIBUTED;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "myParser.l"
{return T_COLUMNS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "myParser.l"
{return T_WAGERS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "myParser.l"
{return T_ADDON;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "myParser.l"
{return T_TOTALPAGES;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "myParser.l"
{return T_TOTALELEMENTS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "myParser.l"
{return T_FIRST;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "myParser.l"
{return T_NUMBEROFELEMENTS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "myParser.l"
{return T_SORT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "myParser.l"
{return T_SIZE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "myParser.l"
{return T_NUMBER;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "myParser.l"
{return T_DIRECTION;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "myParser.l"
{return T_PROPERTY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "myParser.l"
{return T_IGNORECASE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "myParser.l"
{return T_NULLHANDLING;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "myParser.l"
{return T_DESCENDING;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "myParser.l"
{return T_ASCENDING;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "myParser.l"
{return T_LCURLY;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "myParser.l"
{return T_RCURLY;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "myParser.l"
{return T_COMMA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "myParser.l"
{return T_COLON;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "myParser.l"
{return T_LBRUCKET;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "myParser.l"
{return T_RBRUCKET;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 85 "myParser.l"
;       /* skip whitespace */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "myParser.l"
{return T_MINID;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "myParser.l"
{return T_IDDIGIT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 89 "myParser.l"
{return T_BOOLEAN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 90 "myParser.l"
{return T_BOOLEAN1;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "myParser.l"
{return T_INTEGER;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "myParser.l"
{return T_Q;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "myParser.l"
{
                            yylval.str = strdup(yytext);
                            return T_IDENTIFIER;
                        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "myParser.l"
{
                            yylval.str = strdup(yytext);
                            return T_PROPERTY1;
                        }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 104 "myParser.l"
{return T_FLOAT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 105 "myParser.l"
{return T_REAL;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 107 "myParser.l"
{/*ignore whitespace*/}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 108 "myParser.l"
ECHO;
	YY_BREAK
#line 1568 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 371 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 371 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 370);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 108 "myParser.l"


